/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/gbl/myModel-v1.glb --transform --simplify --resolution 1024 
Files: models/gbl/myModel-v1.glb [1.72MB] > C:\movin\programing\GDSC\GDGWEBSITE\gdg-crce_26-27\myModel-v1-transformed.glb [479.4KB] (72%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/myModel-v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[15.105, 1.252, -28.368]} scale={[5.62, 1, 3.57]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} position={[15.125, 0.442, -29.077]} rotation={[-Math.PI / 2, 0, 0]} scale={[12.1, 11.563, 3.496]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.material_2} position={[16.522, 0.588, -22.215]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.071, 9.623, 2.909]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.material_3} position={[15.227, 0.635, -28.954]} rotation={[-Math.PI / 2, 0, 0]} scale={[12.752, 12.185, 3.684]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_5} position={[24.768, 1.011, -35.007]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.772, 0.738, 0.223]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.PaletteMaterial002} position={[15.227, 0.916, -28.237]} rotation={[-Math.PI / 2, 0, 0]} scale={[12.109, 11.57, 3.498]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_7} position={[15.227, 1.007, -34.479]} rotation={[-Math.PI / 2, 0, 0]} scale={[12.752, 12.185, 3.684]} />
    </group>
  )
}

useGLTF.preload('/myModel-v1-transformed.glb')
