/*
Auto-generated by: https://github.com/pmndrs/gltfjsx (then hand-cleaned)
Model: "Polaroid One Step Camera"
Author: riotboy (https://sketchfab.com/DimanRson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/polaroid-one-step-camera-752a1798bd904eafb8d19f605b96d2f7

⚠ CC-BY-4.0 requires ATTRIBUTION wherever the model is shown publicly — keep a
   visible credit to "riotboy / Sketchfab" (e.g. an About/credits line).

Compressed off-line with `gltf-transform optimize --compress meshopt
--texture-compress webp --texture-size 1024` (3.74 MB → ~285 KB). meshopt is
auto-decoded by drei's useGLTF, so no loader changes are needed.
*/
'use client';

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube_polaroid_0: THREE.Mesh;
    Cube015_glass_0: THREE.Mesh;
  };
  materials: {
    polaroid: THREE.MeshStandardMaterial;
    glass: THREE.MeshStandardMaterial;
  };
};

const MODEL_URL = '/models/polaroid-one-step.glb';

/** Raw model, in its own coordinate space. Fit (scale/position/rotation) is
 *  applied by the wrapping group in PolaroidScene, alongside the camera path. */
export default function PolaroidOneStep() {
  const { nodes, materials } = useGLTF(MODEL_URL) as unknown as GLTFResult;
  return (
    <group dispose={null}>
      <mesh
        name="Cube_polaroid_0"
        castShadow
        receiveShadow
        geometry={nodes.Cube_polaroid_0.geometry}
        material={materials.polaroid}
        position={[-0.113, 0.092, -0.012]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.451}
      />
      <mesh
        name="Cube015_glass_0"
        castShadow
        receiveShadow
        geometry={nodes.Cube015_glass_0.geometry}
        material={materials.glass}
        position={[0.594, 0.959, 1.463]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.334}
      />
    </group>
  );
}

useGLTF.preload(MODEL_URL);
